### ISSUE TITLE
In place type change results in inaccurate math results

### ISSUE THREAD

**Issue by barryple** [arturo-lang/arturo#1607] opened 2024-04-22 14:29 UTC
Converting a floating point number to an integer and then adding it to a negative number gives incorrect results.

$> x: 1.1

$> to :integer x + neg(3)
=> -1

results should be 
$> 1 + neg(3)
=> -2

I'm running the Linux arm64 mini version v/0.9.83 @ 2023-02-10T16:02:07-05:00 from the download page.

**Comment by drkameleon** [comment] 2024-04-22 14:39
First of all, hi! 
And welcome to our community! 😉 

What you mention seems ... suspicious, so I tried to test it for myself.
And apparently, you are 100% right.

That's exactly what the returned results are.

However, I tried the exact same thing in Ruby and it seems like the results (for this type of operation) is identical, so... I'd have to investigate and see what the best practice should be in this sort of cases:

<img width="355" alt="Screenshot 2024-04-22 at 16 35 22" src="https://github.com/arturo-lang/arturo/assets/1265028/6d4c6716-ffb2-4362-9943-28d82ea12791">

Now, that being said, if you *want* to get the result you mentioned (`-2`), I'd use **[`round`](https://arturo-lang.io/documentation/library/numbers/round/)** first - that is *before* converting `to :integer`:

<img width="395" alt="Screenshot 2024-04-22 at 16 34 34" src="https://github.com/arturo-lang/arturo/assets/1265028/f610923c-b805-4efe-b6df-2ca2b35137d2">

I believe this does the trick! 😉

**Comment by RickBarretto** [comment] 2024-05-19 21:13
As @drkameleon said, welcome to our community @barryple. Sorry for replying this now, I just notice right now the why of the confusion, and I'm closing this issue.

---

I already have read this, but re-reading some issues I decided to close it.
This is not a bug. The main issue here is not the `round` or the conversion to `:integer` itself, but the precedence.

Arturo's precedence is from right to left, so what you need it not the `round` function, but just replace the precedence.

Let's take this Python example:
![image](https://github.com/arturo-lang/arturo/assets/78623871/317f1886-1191-4903-8374-6fa04d41baa5)

Now, let's see what is happening in Arturo:
![image](https://github.com/arturo-lang/arturo/assets/78623871/3f7e5985-9a56-43d5-9f77-7fedf7717b88)

The stack process:
```
1. []
2. [3]
3. [3 neg]
4. [(-3)]
5. [(-3) + (to :integer x)]
6. [(-3) + 1]
7. [-2]
```

**Closed by RickBarretto** 2024-05-19 21:13 UTC
Labels: bug, open discussion, :integer
