### ISSUE TITLE
windows binary misses the sqlite3_64.dll

### ISSUE THREAD

**Issue by vrescobar** [arturo-lang/arturo#267] opened 2021-04-12 08:10 UTC
**Describe the bug**
Precompiled binary for windows misses a sqlite dll. It was the first contact with this lang.

**To Reproduce**
1. [Download windows binary 0.9.7.4](https://arturo-lang.io/#download)
2. Uncompress
4. open CMD and run from DOS Shell

**Expected behavior**
Run out of the box, perhaps statically compiled (idk whether it should come a GUI or a REPL shell)

**Screenshots**
![grafik](https://user-images.githubusercontent.com/6759126/114362127-479fca80-9b77-11eb-8392-d2110566e295.png)

**Desktop (please complete the following information):**
Windows x64

**Smartphone (please complete the following information):**
NA

**Additional context**
In addition, the binary is compressed as tar.gz which is common on *nix OS but uncommon in windows world (would recommend a bare .zip)

**Comment by drkameleon** [comment] 2021-04-12 08:50
Hi! And thanks a lot for the letting me know!

The issue is - pretty much - already known, but given that my development machine is not Windows (I'm working on a Mac and using Linux extensively as well) it hasn't been too easy to spot.

I know there are some DLLs missing, but I'll have to figure out how to do it. First thought is to simply serve them along the binary, but this would make the whole thing less portable than I'd want it to be. The next thought would be to static link the necessary libraries. But this, would obviously lead to bigger binaries.

First of all, let's see what the missing libraries in your case are....

- https://arturo-lang.s3.amazonaws.com/sqlite3_64.dll.zip
- https://arturo-lang.s3.amazonaws.com/pcre64.dll.zip
- https://arturo-lang.s3.amazonaws.com/libcrypto-1_1-x64.dll.zip
- https://arturo-lang.s3.amazonaws.com/libssl-1_1-x64.dll.zip

These are the most likely DLLs missing. Could you please download them and unzip them (in the same folder as the main Arturo binary) and let me know how it went? (The ideal thing would be to only unzip the ones that are missing, one-by-one, so that we know which ones are *actually* needed)

**Comment by drkameleon** [comment] 2021-04-16 08:40
As of now, and until properly resolved, all the latest nightly builds and official releases for Windows include the necessary DLLs: https://github.com/arturo-lang/arturo/releases/tag/v0.9.75

**Comment by drkameleon** [comment] 2021-04-28 09:22
Since I haven't received any update on the above, I'm closing the issue considering it solved.

If there's still any problem, just let me know and we'll re-open it. :)

**Closed by drkameleon** 2021-04-28 09:22 UTC
Labels: 3rd-party, bug, windows, wontfix
