### ISSUE TITLE
filter is not always working in 0.9.83

### ISSUE THREAD

**Issue by nosly** [arturo-lang/arturo#988] opened 2023-02-13 14:12 UTC
This code doesn't work:
deJunk: $[arr, keyword] [
    filter 'arr 'x [
        if? in? keyword x -> x
    ]
]
leftTxt: @["mini-main.site:8080"]
deJunk leftTxt, "mini-main.site"

It works if changed to:
leftTxt: @["mini-main.site:8080"]
filter 'leftTxt, 'x [
    if? in? "mini-main.site" x -> x
]
print leftTxt

In 0.9.80, it worked fine

**Comment by drkameleon** [comment] 2023-02-14 10:33
@nosly Hi! 😄 

And thanks a lot for the issue!

To be perfectly honest, I'm not 100% sure what you're trying to achieve here.

**A couple of remarks off the top of my head:**

- When using `if?`, it actually expects a trailing `else`. So, when it's just an if clause, you'd better use `if`.
- `if? in? "mini-main.site" x -> x` seems to actually return `x` if the condition is true. `filter`, by definitios, works by filtering all items for which the condition is true so... something like that would be more meaningful and to-the-point (I think):
  ```red
  filter 'arr 'x -> in? keyword x
  ```
- Your use case is an interesting one and I can probably imagine why. Actually, you are using `filter` for in-place filtering, but in your specific case you are using it on a passed parameter. I think that's what's causing the issue; and the reason why it's not working (I think I could think of a way to make it work for sure) with 0.9.83 is that auto-exportable symbols and scoping for functions has become a tiny bit stricter.

**As a workaround, I would suggest something like this:**

```red
deJunk: $[arr, keyword] [
    filter arr 'x -> in? keyword x
]
leftTxt: @["mini-main.site:8080"]
leftText: deJunk leftTxt, "mini-main.site"
```

------

P.S. All that having been said, of course you remind me to look into symbol exporting from function (as in the case of in-place modification to passed parameters), so... that *is* a valid one! 😉

**Comment by nosly** [comment] 2023-02-14 16:04
@drkameleon Hi! 
Thanks a lot for the detailed reply. Forgot to mention I'm on windows which could bring some bugs of its own;-)

- You are right that it should be written as: `filter 'arr 'x -> in? keyword x`, and functionality-wise my ugly `if?` version should be the same, it is so on windows 0.9.80, but different on 0.9.83(linux/win). As a side note, if you change the `if?` to `if`, it causes segfault, no matter win or linux, 0.9.80 or 0.9.83, maybe this is a different bug to look into
- Your workaround is fine on linux 0.9.83 but causes segfault on windows
> in-place modification to passed parameters
- You are spot on this. It maybe cause some issues here but can be very powerful and handy in certain situations, hope to see this soon

**Comment by drkameleon** [comment] 2023-02-14 17:37
Ahh... Windows, my passion! (just kidding... https://github.com/arturo-lang/arturo/pull/989 lol)

Can you please send me the exact code that segfault's to have a look? (at time, even something negligible may be the culprit).

As for `if?` vs `if` in this particular scenario, I would say it can lead to totally unpredictable bugs. `filter` expects a `true`/`false` value. And `if?` does just that. But not in the way you expect it to do so. Basically, it return `true` if `if` succeded, and `false` otherwise; the only reason being ... so that this true/false is captured by a following `else`. If there is no following `else`, then... we are open for totally hard-to-predict behavior.

In general, the rule is:

- do we have an `else`? use `if?`
- we don't have an `else`? use `if`
- do you simply want to have something like a ternary, value-based `if-else`? use `switch` (alias: `?`). E.g.:
   ```red
   v: true
   x: (v)? -> 1 -> 2 ; if v is true, set x to 1; otherwise, set it to 2
   ```
   
------

P.S. Feel free to ask anything else you may need; in the meantime, we'll surely spot a bug or too, and that's always good so that we can fix it in time 😉

**Comment by nosly** [comment] 2023-02-15 02:45
Here you go:😘
- The `if` segfault:
leftTxt: @["string 1", "string 2", "Hello"]
deJunk: $[arr, keyword] [
    filter 'arr [x][
        if in? keyword x -> x
    ]
]
; v0.9.80 use this
deJunk leftTxt, "Hello"
; v0.9.83 use this
; leftTxt: deJunk leftTxt, "Hello"
print leftTxt

Expected result: string 1 string 2
Actual result: SIGSEGV: Illegal storage access. (Attempt to read from nil?)

- After more tests, your workaround seems not woring on v0.9.83
leftTxt: @["string 1", "string 2", "Hello"]
deJunk: $[arr, keyword] [
    filter 'arr 'x -> in? keyword x
]
deJunk leftTxt, "Hello"
print leftTxt

Expected result: string 1 string 2
Actual result: string 1 string 2 Hello

If we change `deJunk leftTxt, "Hello"` to `leftTxt: deJunk leftTxt, "Hello"`, 
On windows: SIGSEGV: Illegal storage access. (Attempt to read from nil?)
On linux playground: 
timeout: sending signal KILL to command '/var/www/arturo-lang.io/arturo-0.9.83-safe-linux'

**Comment by RickBarretto** [comment] 2023-02-16 15:28
It's not a bug, let me explain!


## The correct implementation

```red
leftTxt: @["string 1" "string 2" "Hello"]

deJunk: $[arr, keyword] [
    filter 'arr 'x  ; you can write [x] instead of 'x as well
        -> in? keyword x
    return arr
]

leftTxt: deJunk leftTxt "Hello"
print leftTxt
; string 1 string 2
```

or 

```red
leftTxt: @["string 1" "string 2" "Hello"]

deJunk: $[arr, keyword] [
    filter arr 'x ; you can write [x] instead of 'x as well
        -> in? keyword x
]


deJunk 'leftTxt "Hello"
print leftTxt
; string 1 string 2
```

## The errors

### Your first code

```red
leftTxt: @["string 1", "string 2", "Hello"] 

deJunk: $[arr, keyword] [  
	filter 'arr [x][     
		if in? keyword x -> x 
	]  
]

deJunk leftTxt, "Hello"
print leftTxt
```

### Understanding filter’s condition

This code above returns a:

```r
timeout: sending signal KILL to command '/var/www/arturo-lang.io/arturo-0.9.83-safe-linux'
```

**Timeout** is a security feature to avoid a infinite recursion or memory consume. This problem in on `if` use here, that returns an unexpected value to `filter`.

`filter` gets a `collection`, `params` and `condition`, `condition` is the part we are caring about here. 
Basically, `condition` should return a `:logical` type, it means a `true`, `false` or `maybe`. When you use `if [condition] -> value`, you’re actually returning `value`, not the validation itself.

Read it `if in? keyword x -> x` as “if item x is in keyword, return x”, but filter don’t want `x`, it wants a `:logical` type.

So, fixing it:

```red
leftTxt: @["string 1", "string 2", "Hello"] 

deJunk: $[arr, keyword] [  
	filter 'arr [x][
		in? keyword x
	]  
]

deJunk leftTxt "Hello"
print leftTxt
```

BUT, now, it’s returning `string 1 string 2 Hello`, so what's next?

### Modifying leftTxt

Whaaaat!? What is happening here? Let’s re-write this with a `print` inside this function:

```red
leftTxt: @["string 1", "string 2", "Hello"] 

deJunk: $[arr, keyword] [  
	filter 'arr 'x        
		-> in? keyword
	print arr
]

deJunk leftTxt "Hello"
print leftTxt
```

It’s outputing:
```
string 1 string 2
string 1 string 2 Hello
```

So, the `filter` is now working, but it isn’t assigning the `leftTxt`. Let’s fix it!

Now, we have two ways to do it, the first is assign in-place and the second is re-assign manually returning a value.

#### In-place way

```red
leftTxt: @["string 1", "string 2", "Hello"] 

deJunk: $[arr, keyword] [  
	filter 'arr 'x        
		-> in? keyword x
]

deJunk leftTxt "Hello"
print leftTxt
```

To modify in-place, you must pass your object as a reference to your function. Let’s try!

```red
leftTxt: @["string 1", "string 2", "Hello"] 

deJunk: $[arr, keyword] [  
	filter 'arr 'x        
		-> in? keyword x
]

deJunk 'leftTxt "Hello"
print 'leftTxt
```

BUT, what we get:

```r
>> Runtime | File: main.art  
error | Line: 6  
|  
| value points to a readonly constant: arr  
| which cannot be modified in-place
```

Define `arr` here as a `:literal` is a big mistake, it’s because when you pass a value by reference you can’t modify this parameter itself, being a read-only variable. You cannot modify a reference with another.
I know, it’s a bit confuse, but just think, pass using `:literal` for in-place modify, but don’t use `:literal` for parameters inside this function. 

To solve it, instead of define `arr` as a `:literal`, you’ll pass your object as a `:literal` to this function, like this: `deJunk 'leftTxt "Hello"`.

Fixing it, now we have:

```red
leftTxt: @["string 1", "string 2", "Hello"] 

deJunk: $[arr, keyword] [  
	filter arr 'x      
		-> in? keyword x
]

deJunk 'leftTxt "Hello"
print leftTxt
```

And, we finally have the right output!

```
string 1 string 2
```

#### Manual way, returning a value

```red
leftTxt: @["string 1", "string 2", "Hello"] 

deJunk: $[arr, keyword] [  
	filter 'arr 'x        
		-> in? keyword x
	print arr
]

deJunk leftTxt "Hello"
print leftTxt
```

Let’s re-assign `leftTxt` and return `arr`!

```red
leftTxt: @["string 1", "string 2", "Hello"] 

deJunk: $[arr, keyword] [  
	filter 'arr 'x        
		-> in? keyword x
	return arr
]

leftTxt: deJunk leftTxt "Hello"
print leftTxt
```

Wow, it’s working!

```
string 1 string 2
```

But not so fast! Before celebrating, let me explain something.

- Don’t `return 'arr`, it’ll actually return a `:literal` and not your array, ok?
- In this code, I’m using `'arr` as `filter`‘s parameter, but it’s because I’m modifying the `deJunk`‘s `arr` value and not `leftTxt`, this is why I must `return` it.
- You can use a simpler alternative code to return, look the differences:

```red
leftTxt: @["string 1", "string 2", "Hello"] 

deJunk: $[arr, keyword] [  
	return filter arr 'x        
		-> in? keyword x
]

leftTxt: deJunk leftTxt "Hello"
print leftTxt
```



## Your second code

```red
leftTxt: @["string 1", "string 2", "Hello"]

deJunk: $[arr, keyword] [
    filter 'arr 'x -> in? keyword x
]

deJunk leftTxt, "Hello"
print leftTxt
```

As the first one, the same mistake `'arr` inside `deJunk` and not passing `leftTxt` as `:literal` for in-place assign.

What is happening here? Let’s re-write this with a `print` inside this function:

```red
leftTxt: @["string 1", "string 2", "Hello"]

deJunk: $[arr, keyword] [
    filter 'arr 'x -> in? keyword x
    print arr
]

deJunk leftTxt, "Hello"
print leftTxt
```

We got the output:
```
string 1 string 2  
string 1 string 2 Hello
```

That means that you’re modifying the `deJunk`’s `arr` variable, but you’re not actually modifying `leftTxt` and even you’re not returning any value from `deJunk`.

## Final considerations

- You can use either, `[x]` and `'x` as the second parameter of `filter`
- You can’t use the function’s parameter as a `:literal`, eg.: `'arr`, pass your object to function as a `:literal` instead
- `filter`‘s `condition` should get a `:logical` type, don’t return other type
- You can use `return` if you want to
- You can use `->` as sugar syntax for `[]` as you used on your second version
- You don't need `,` to separate things, but you can use as well
- Also, you can highlight the code for better comprehension

How to highlight code on github:

![image](https://user-images.githubusercontent.com/78623871/219410188-b5a443b3-b069-4596-a41c-d001faaf19e6.png)
Note: I'm current using `red` as highlight, because Github doesn't recognize Arturo's syntax.

**Comment by drkameleon** [comment] 2023-02-16 16:58
@RickBarretto Wow. Just wow. 🚀

**Comment by celtic-coder** [comment] 2023-02-16 19:13
Yes, @RickBarretto, a very clear, comprehensive, and well thought-out explanation!

**Comment by RickBarretto** [comment] 2023-02-16 19:18
Thank you, guys! @drkameleon @celtic-coder 😄

**Comment by nosly** [comment] 2023-02-17 04:08
@RickBarretto Wow, what a master piece to showcase the elegance of the language and the excellent writing style for technical explanations.  You are doing a great service to the community, thank you very much!🤝

**Comment by nosly** [comment] 2023-02-17 07:55
- Question: Given a list of unwanted keywords, remove them from leftTxt using `loop`
```red
keywords: @["foo" "bar"]
leftTxt: @["foo" "bar" "Hello"]
```
- Applying what we learned from @RickBarretto:

```red
deJunk: function [arr, keyword] [
    filter arr 'x -> in? keyword x
]

loop keywords 'keyword [
    deJunk 'leftTxt, keyword
	; or explicitly do the assignment
	; leftTxt: deJunk leftTxt, keyword
    print ["Inside loop:" leftTxt]
]
prints "Result: "
print leftTxt
```

@drkameleon, btw, with this kind of tricks, is the "in-place modification to passed parameters" enhancement request still necessary?

**Comment by drkameleon** [comment] 2023-02-17 09:30
@nosly You have a very good point. The thing is there are a couple of things that changed between 0.9.80 and the current version, one of which has to do with how values are treated ("original" ones vs copies) along with some slight changes in scoping rules. And even though we may not need to change things, properly speaking, how to to deal with this kind of scenarios must be totally transparent (pretty much along the lines of how @RickBarretto wonderfully explained it! 😉 )

So, let's see all this discussion here as food for thought. And very constructive food for thought, for that matter... 🚀

**Comment by drkameleon** [comment] 2023-02-17 09:36
> Note: I'm current using red as highlight, because Github doesn't recognize Arturo's syntax.

A rather irrelevant side-comment on my side: I'm totally willing to make Arturo highlight-able, but... the [Linguist](https://github.com/github/linguist) team (what Github uses for recognizing languages/syntaxes/etc) is quite picky as to what they accept as a new syntax highlighter (and quite rightly so, I guess); so, unfortunately, until we have a substantial number of repositories written in Arturo, I don't see any real chance of Arturo support being integrated. But, everything in its due time! 😉

**Comment by RickBarretto** [comment] 2023-02-17 12:06
Thank you @nosly !! I'm happy to read it!

About the loop, you can also implement this feature inside your function to avoid create a loop every time.

Instead of remove just one item for each function call, you can define `keyword` as an optional `:block` type. If it's a `:block` type, then it should remove every item from this block.
And, also, to remove an entire block exact as it is, you can create an attribute called `.instance`.

Just a tip, you can improve a lot your function doing it.

In case of some question, you can text here, or on Discord. I would be happy helping you. 🙂

I just don't write this code now, because I'm writing from my mobile now. But, I can when I come to home.

**Comment by nosly** [comment] 2023-02-17 14:18
@RickBarretto, can't wait to try your magics out, here it goes:
```red
keywords: @["foo" "bar"]
leftTxt: @["foo" "bar" "Hello"]

deJunks: $[arr tobeDeleted] [
    remove arr tobeDeleted
]
print deJunks leftTxt keywords
```
Output:
`Hello`

However, if we change to `leftTxt: @["foo++" "bar--" "Hello"]`, output will be:
`foo++ bar-- Hello`

In other words, this version is only good for exact match (`foo`), whereas the loop version will match `.*foo.*`

**Comment by RickBarretto** [comment] 2023-02-18 02:42
@nosly 
Another long reading, but I hope it is very informative.

## Final code

```red
deJunk: function [arr :literal keywords :any] [ 
    
    ;; description: { 
    ;;   remove every item from 'arr that matches
    ;;   with some 'keywords's sub-string.
    ;;
    ;;   !NOTE: 'keywords can be just a :string or a :block of :string
    ;; }
    ;;
    ;;   options: [
    ;;      instance: « remove a :block as it is, instead of iterate every item of it
    ;;   ]
    ;;
    ;;   example: [
    ;;      base: @[ "1" "2" "string 1" "string 2" ["1" "2"] "Hello"]
    ;;      var1: base
    ;;      var2: base
    ;;      var3: base
    ;;      var4: base
    ;;
    ;;      deJunk 'var1 "string"; removes "string 1" and "string 2"
    ;;      deJunk 'var2 ["1" "2"]; removes "string 1", "string 2", "1", "2", ["1"] and ["2"]
    ;;      deJunk.instance 'var3 "string"; removes "string 1" and "string 2"
    ;;      deJunk.instance 'var4 ["1" "2"]; removes ["1" "2"]
    ;; ]
    ;;

    if? attr? 'instance
        -> filter arr 'x -> or? 
             in? keywords x 
             equal? keywords x
            
    else [
        if? block? keywords
	        -> loop keywords 'keyword
	        -> filter arr 'x 
		        -> in? keyword x   
    	else
    	    -> filter arr 'x 
	    	    -> in? keywords x
    ]
]
```

## My apologies for a little confusion

First, my bad, I failed doing a reference with `remove`, I wasn't saying you to use this function exactly, but to copy the form you can use it. Lol! Again, really, my bad! I wasn’t clear as I should.

`remove` and `deJunk` are similar but very different functions. While `remove` just removes an item that matches with the exact same string, `deJunk` removes an item with a sub-string matching inside this string. So, if you pass `"string"` as the `keyword`, your code should remove `"string 1"` and `"string 2"` for example.
What I was talking about `remove`, was the way he deals with `:blocks` to avoid do loops.

Said that, let's see *✨the magic happening!✨*

---

## *✨ The magic! ✨*

Here is our latest code:

```red
deJunk: function [arr, keyword] [
    filter arr 'x -> in? keyword x
]

loop keywords 'keyword [
    deJunk 'leftTxt, keyword
	; or explicitly do the assignment
	; leftTxt: deJunk leftTxt, keyword
    print ["Inside loop:" leftTxt]
]
prints "Result: "
print leftTxt
```

### Our objectives are:
- [ ] remove loop
- [ ] loop for `:block` type as parameter
- [ ] create a option to don’t loop the `:block`‘s items

#### How we gonna do it

Arturo has a philosophy of be a language without syntax, every thing here is a word. So, let’s see this as just words.
Every function is a verb, and a verb can have an adverb, that modifies its behavior. In our case, `deJunk` is a verb and `instance` is an adverb. 

But, why I’m saying it?? Because in some cases we don’t want to remove every item given by a `:block`, but instead of it, the `:block` itself, and this will be the role of `instance` here. So, let’s go!

### The code

#### Cleaning code

```red
deJunk: $[arr keyword] [
    filter arr 'x
        -> in? keyword x
]
```

#### Adding `:block` support

##### Adding type checkers

Here we add this internal type checker:

```red
deJunk: function [arr keywords] [
	if? block? keywords [
	
	]
	else [
		filter arr 'x -> in? keywords x
	]
]
```

- Remembering, use `if?` (not `if`) when you need an `else` block.
- Use `block?` instead of `is? :block`, it makes easier to read

Making it more verbose, why not?

```red
deJunk: function [arr :literal keywords :any] [
	if? block? keywords [
	
	]
	else [
		filter arr 'x -> in? keywords x
	]
]
```

- Add types to our function’s header creates a automatic type check and more, it makes easier to understand what is happening when check with `info` function as I’ll show later

##### Let’s see how it’s going

Running it:

```red
deJunk: function [arr :literal keywords :any] [
	if? block? keywords [
	
	]
	else [
		filter arr 'x -> in? keywords x
	]
]

var1: @["string 1" "string 2" "Hello"]
var2: @["string 1" "string 2" "Hello"]

deJunk 'var1 "string"
deJunk 'var2 ["1" "2"]
print var1
print var2
```

We get a:

```
Hello  
string 1 string 2 Hello
```

As we expected, it isn’t returning anything for `:block`s, but returning the right value for `:string`s. But, we really want the same value in this case, so let’s implement it!

##### Creating a implementation for loop `:block`s

And then, the implementation, creating a internal loop:

```red
deJunk: function [arr :literal keywords :any] [
	if? block? keywords [
		loop keywords 'keyword
			-> filter arr 'x -> in? keyword x
	]
	else [
		filter arr 'x -> in? keywords x
	]
]

var1: @["string 1" "string 2" "Hello"]
var2: @["string 1" "string 2" "Hello"]

deJunk 'var1 "string"
deJunk 'var2 ["1" "2"]
print var1
print var2
```

Output:

```
Hello  
Hello
```

Alright, two finished objectives! 🚀

- [x] remove loop
- [x] loop for `:block` type as parameter

#### Adding `.instance` attribute (our adverb)

```red
deJunk: function [arr :literal keywords :any] [
    
    if? attr? 'instance [
        filter arr 'x [ 
            or? 
              in? keywords x 
              equal? keywords x
        ]
    ] else [
        if? block? keywords [
	        loop keywords 'keyword
	            -> filter arr 'x -> in? keyword x   
    	]
    	else [
    	    filter arr 'x -> in? keywords x
    	]   
    ]
]
```

- Use `attr? 'myAttribute'` to know if your attribute exists
- In this case, I checked if `x` is in or is equal to `keywords`. `equal?` is used here for `:block` types.

More one objective done!
- [x] create a option to don’t loop the `:block`‘s items

#### Finishing our function

##### Improving the reading of the code

```red
deJunk: function [arr :literal keywords :any] [  

    if? attr? 'instance
        -> filter arr 'x -> or? 
             in? keywords x 
             equal? keywords x
            
    else [
        if? block? keywords
	        -> loop keywords 'keyword
	        -> filter arr 'x 
		        -> in? keyword x   
    	else
    	    -> filter arr 'x 
	    	    -> in? keywords x
    ]
]
```

- I just replaced blocks `[]` with arrow’s sugar syntax `->`
	- Be careful using it, you can’t put more than one statement inside an arrow
- Also, I took care with indentation. I don’t want to make a mess abusing of it.

##### Testing the final result

```
deJunk: function [arr :literal keywords :any] [  

    if? attr? 'instance
        -> filter arr 'x -> or? 
             in? keywords x 
             equal? keywords x
            
    else [
        if? block? keywords
	        -> loop keywords 'keyword
	        -> filter arr 'x 
		        -> in? keyword x   
    	else
    	    -> filter arr 'x 
	    	    -> in? keywords x
    ]
]

base: @[ "1" "2" "string 1" "string 2" ["1" "2"] "Hello"]

var1: base
var2: base
var3: base
var4: base
var5: remove.instance base ["1" "2"]

deJunk 'var1 "string"
deJunk 'var2 ["1" "2"]
deJunk.instance 'var3 "string"
deJunk.instance 'var4 ["1" "2"]
deJunk.instance 'var5 ["1" "2"]
print var1; removes "string 1" and "string 2"
print var2; removes "string 1", "string 2", "1", "2", ["1"] and ["2"]
print var3; removes "string 1" and "string 2"
print var4; removes ["1" "2"]
print var5; removes nothing
```

Aaannnd, with this we get:

```
1 2 [1 2] Hello  
Hello  
1 2 [1 2] Hello  
1 2 string 1 string 2 Hello  
1 2 string 1 string 2 Hello
```

Everything working well, let’s add documentation now!

#### Final

```red
deJunk: function [arr :literal keywords :any] [ 
    
    ;; description: { 
    ;;   remove every item from 'arr that matches
    ;;   with some 'keywords's sub-string.
    ;;
    ;;   !NOTE: 'keywords can be just a :string or a :block of :string
    ;; }
    ;;
    ;;   options: [
    ;;      instance: « remove a :block as it is, instead of iterate every item of it
    ;;   ]
    ;;
    ;;   example: [
    ;;      base: @[ "1" "2" "string 1" "string 2" ["1" "2"] "Hello"]
    ;;      var1: base
    ;;      var2: base
    ;;      var3: base
    ;;      var4: base
    ;;
    ;;      deJunk 'var1 "string"; removes "string 1" and "string 2"
    ;;      deJunk 'var2 ["1" "2"]; removes "string 1", "string 2", "1", "2", ["1"] and ["2"]
    ;;      deJunk.instance 'var3 "string"; removes "string 1" and "string 2"
    ;;      deJunk.instance 'var4 ["1" "2"]; removes ["1" "2"]
    ;; ]
    ;;

    if? attr? 'instance
        -> filter arr 'x -> or? 
             in? keywords x 
             equal? keywords x
            
    else [
        if? block? keywords
	        -> loop keywords 'keyword
	        -> filter arr 'x 
		        -> in? keyword x   
    	else
    	    -> filter arr 'x 
	    	    -> in? keywords x
    ]
]
```

Try to run `info 'deJunk` now and see what happens! 😉
Also, you can see more about functions [here](https://arturo-lang.io/documentation/library/converters/function/).

**Comment by RickBarretto** [comment] 2023-02-18 02:45
> In other words, this version is only good for exact match (foo), whereas the loop version will match .*foo.*

Just an addendum, `remove` isn't what you're looking for. As you said, it matches good for exact form.
The right form continues being filtering...

**Comment by drkameleon** [comment] 2023-02-18 09:44
@RickBarretto Awesomeness, again! 😲  What can I say. Extremely clear and to-the-point. 👍 

> output is empty, why? Because deJunk here has no return value, or is it possible to add proper return value in the function so that this shorthand will work?

Basically, the function returns nothing (it does all the processing *in-place*), so in turn **print** has nothing to... print.

A quick workaround - if I haven't misread the code - would be to add a `return var 'arr` at the end of `deJunk`.

Like this:
```red
deJunk: function [arr :literal keywords :any] [ 
    if? attr? 'instance
        -> filter arr 'x -> or? 
             in? keywords x 
             equal? keywords x
            
    else [
        if? block? keywords
	        -> loop keywords 'keyword
	        -> filter arr 'x 
		        -> in? keyword x   
    	else
    	    -> filter arr 'x 
	    	    -> in? keywords x
    ]
    return var 'arr
]
```

Given that `'arr` is a `:literal` (think of it as a value pointer), what **[`var`](https://arturo-lang.io/documentation/library/core/var/)** does here is access the value it points to.

To get the idea a bit better, let's think in terms of C:

- if `a` is an `:integer` (`int`) variable
- the pointer to it, it's "address" (`&a`) would be `'a`
- and if we already have a pointer to a variable (`int* pc = &a`), we can get the value it points to using `var` (that would be `*pc`, again in C 😉 )

I hope I didn't over-complicate things 😄

**Comment by nosly** [comment] 2023-02-19 07:59
@drkameleon @RickBarretto Enjoy this learning tour so much, thank you!☺❤️

> I hope I didn't over-complicate things

Not at all. If C was this terse and expressive, we may see a very different landscape for programming language. 

When trying the code, `return var 'arr` doesn't seem to work as intended
```red
deJunk: function [arr :literal keywords :any] [ 
    if? attr? 'instance
        -> filter arr 'x -> or? 
             in? keywords x 
             equal? keywords x
            
    else [
        if? block? keywords
	        -> loop keywords 'keyword
	        -> filter arr 'x 
		        -> in? keyword x   
    	else
    	    -> filter arr 'x 
	    	    -> in? keywords x
    ]
    return var 'arr
]
base: @[ "1" "2" "string 1" "string 2" ["1" "2"] "Hello"]
var1: base

print join @["base => " base]
prints "print -> deJunk 'var1 => "
print -> deJunk 'var1 "string"; removes "string 1" and "string 2"
print join @["var1 => " var1]
```
Output:
```red
base => [1 2 string 1 string 2 [1 2] Hello]
print -> deJunk 'var1 => var1 
var1 => [1 2 [1 2] Hello]
```
If we change `return var 'arr` to `return arr`, result is the same. Maybe it's time for @RickBarretto to do the magic. 😎

**Comment by RickBarretto** [comment] 2023-02-20 03:29
@nosly Sorry for the delay in answering.

I'll be AFK a little, but I promise give you a decent answer very soon.

I'm on my mobile, so I can't test things now. But, this code itself is working fine.
When you ran `print -> deJunk 'var1 "string"` it removed the variables that contained the sub-string "string" inside of them.

So, the remainder is ["1", "2", [ "1", "2"], "hello"], not wrong here.

But, I think strange you mention about `return var 'arr`and `return arr`, they should have different behaviors. But, no worries we'll test soon it, and if wrong, fix soon too.

**Comment by nosly** [comment] 2023-02-20 04:15
@RickBarretto Thanks a lot! No hurry, please take your time to it. ☺

**Comment by drkameleon** [comment] 2023-02-20 09:51
> @drkameleon @RickBarretto Enjoy this learning tour so much, thank you!☺❤️
> 
> > I hope I didn't over-complicate things
> 
> Not at all. If C was this terse and expressive, we may see a very different landscape for programming language.
> 
> When trying the code, `return var 'arr` doesn't seem to work as intended
> 
> ```red
> deJunk: function [arr :literal keywords :any] [ 
>     if? attr? 'instance
>         -> filter arr 'x -> or? 
>              in? keywords x 
>              equal? keywords x
>             
>     else [
>         if? block? keywords
> 	        -> loop keywords 'keyword
> 	        -> filter arr 'x 
> 		        -> in? keyword x   
>     	else
>     	    -> filter arr 'x 
> 	    	    -> in? keywords x
>     ]
>     return var 'arr
> ]
> base: @[ "1" "2" "string 1" "string 2" ["1" "2"] "Hello"]
> var1: base
> 
> print join @["base => " base]
> prints "print -> deJunk 'var1 => "
> print -> deJunk 'var1 "string"; removes "string 1" and "string 2"
> print join @["var1 => " var1]
> ```
> 
> Output:
> 
> ```red
> base => [1 2 string 1 string 2 [1 2] Hello]
> print -> deJunk 'var1 => var1 
> var1 => [1 2 [1 2] Hello]
> ```
> 
> If we change `return var 'arr` to `return arr`, result is the same. Maybe it's time for @RickBarretto to do the magic. 😎

Mea culpa!

Could you re-try with `return var arr`?

**Comment by nosly** [comment] 2023-02-20 10:58
@drkameleon Yes, that nails it!😎

**Comment by drkameleon** [comment] 2023-02-20 11:08
> @drkameleon Yes, that nails it!😎

In the end, I got confused myself!

Basically, the explanation goes like this:

- you pass `var1` to `deJunk` as a literal (to not overcomplicate things, let's imagine we just set `arr` as `"var1"`; yep, *literals* are actually strings)
- then we do our processing using `arr` (which is a literal value)
- now, how `var` works: basically, it takes the *name* of a variable (call it literal/string/whatever, doesn't matter; it's still a *string*) and returns its value)... soooo, since `arr` is *already* set to the name of the variable we are changing (var1), we just need the value of `arr` (= "var1") and not `'arr` (= "arr"), which is pretty much nonsense 😉

**Comment by nosly** [comment] 2023-02-20 12:40
@drkameleon The following code: 
```red
print join @["var1 => " var1]
print ~"var1 => |var1|"
print -> join @["var1 => " var 'var1]
```
gives same output:
`var1 => [1 2 [1 2] Hello]`

Note the last one with `var 'var1`, how is this different from `return var arr`?

**Comment by drkameleon** [comment] 2023-02-20 12:53
`var1` = look up the symbol `var1` in the symbol table and return its value
`var 'var1` = look up the symbol with the name "var1" in the symbol table and return its value

Practically they are identical.

You could say that for every `x + 1`, you are actually writing something like `(var "x") + 1` 😉

**Comment by drkameleon** [comment] 2023-02-20 12:56
**(Hopefully) constructive sidenote:**

Since every symbol (`a`, `fn`) is actually either loading the value or calling a function (*if* that symbol corresponds to a function), the only reasons to call `var` as far as I can tell are two:

- in-place modifications (like you do)
- get the value of a function, e.g. `myNewPrint: var 'print` (without this, it wouldn't make any sense, since `myNewPrint: print` would actually *call* print, not get it as a *value*)

**Comment by drkameleon** [comment] 2023-02-20 13:02
**Another (slightly more advanced) example:**

```red
got: split.words input "give me an operation and 2 numbers: "

operation: var got\[0]

print call operation @[
    to :integer got\[1] 
    to :integer got\[2]
]
```

**The above code in action:**

<img width="610" alt="Screenshot 2023-02-20 at 14 02 25" src="https://user-images.githubusercontent.com/1265028/220116174-3c6d83dd-ae8f-4c00-ab32-38b4ae22a011.png">

**Comment by nosly** [comment] 2023-02-23 02:47
@RickBarretto @drkameleon Thank you very much for the detailed explanations, much appreciated❤️

**Comment by drkameleon** [comment] 2023-02-23 09:23
So, that being said... I'm closing this issue.

But obviously, feel free to ask anything else you need! 😉

**Closed by drkameleon** 2023-02-23 09:23 UTC
Labels: bug
